version: '3'
services:
  db:
    image: postgres:10.1-alpine
  backend:
    build:
      context: ../orelrb-backend
      dockerfile: Dockerfile-dev
    command: bash -c "rm -rf /usr/src/app/tmp/pids/server.pid;
      bundle exec rails s -p 4000 -b '0.0.0.0'"
    image: backend:1
    container_name: backend_1
    volumes:
      - ../orelrb-backend:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db
