version: '3'
services:
  nginx-proxy:
    image: nginx:1.13.8-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./nginx/proxy/certs:/etc/nginx/certs:ro
    restart: unless-stopped

  nginx-gen:
    image: jwilder/nginx-gen:latest
    container_name: nginx-gen
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./nginx/proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: unless-stopped

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./nginx/proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/proxy/certs:/etc/nginx/certs:rw
    restart: unless-stopped
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen

  nginx-orelrb:
    image: nginx:1.13.8-alpine
    container_name: nginx-orelrb
    volumes:
      - ./nginx/conf.d/nginx-orelrb.conf:/etc/nginx/conf.d/nginx-orelrb.conf
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: orelrb.centralus.cloudapp.azure.com
      LETSENCRYPT_HOST: orelrb.centralus.cloudapp.azure.com
      LETSENCRYPT_EMAIL: karpinovsky@gmail.com

  frontend:
    image: orelrb/frontend:latest
    container_name: frontend
    command: sh -c "ln -s node_modules/react-scripts/bin/react-scripts.js node_modules/.bin/react-scripts;
      yarn start"
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: frontend
      VIRTUAL_PORT: 3000
    depends_on:
      - backend

  backend:
    image: orelrb/backend:latest
    container_name: backend
    command: sh -c "rm -rf /usr/src/app/tmp/pids/server.pid;
      bundle exec rails s -p 4000 -b '0.0.0.0'"
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: backend
      VIRTUAL_PORT: 4000
    depends_on:
      - db

  db:
    image: postgres:10.1-alpine
    container_name: db
    restart: unless-stopped
