version: '3'
services:
  db:
    image: postgres:10.1-alpine
    container_name: db
  frontend:
    build:
      context: ../orelrb-frontend
      dockerfile: Dockerfile.dev
    command: sh -c "ln -s node_modules/react-scripts/bin/react-scripts.js node_modules/.bin/react-scripts;
      yarn start"
    image: orelrb/frontend:latest
    container_name: frontend
    volumes:
      - ../orelrb-frontend:/usr/src/app
    ports:
      - "3000:3000"
  backend:
    build:
      context: ../orelrb-backend
      dockerfile: Dockerfile.dev
    command: sh -c "rm -rf /usr/src/app/tmp/pids/server.pid;
      bundle exec rails s -p 4000 -b '0.0.0.0'"
    image: orelrb/backend:latest
    container_name: backend
    volumes:
      - ../orelrb-backend:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db
