version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker/sock:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    restart: unless-stopped

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes-from:
      - nginx-proxy

  nginx-orelrb: nginx
    image: nginx:1.13.8-alpine
    container_name: nginx-orelrb
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: orelrb.centralus.cloudapp.azure.com
      LETSENCRYPT_HOST: orelrb.centralus.cloudapp.azure.com
      LETSENCRYPT_EMAIL: karpinovsky@gmail.com
    depends_on:
      - backend

  db:
    image: postgres:10.1-alpine
    container_name: db
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: orelrb.centralus.cloudapp.azure.com
      LETSENCRYPT_HOST: orelrb.centralus.cloudapp.azure.com
      LETSENCRYPT_EMAIL: karpinovsky@gmail.com

  backend:
    build:
      context: ../orelrb-backend
      dockerfile: Dockerfile.dev
    command: bash -c "rm -rf /usr/src/app/tmp/pids/server.pid;
      bundle exec rails s -p 4000 -b '0.0.0.0'"
    image: backend:1
    container_name: backend
    restart: unless-stopped
    volumes:
      - ../orelrb-backend:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      VIRTUAL_HOST: orelrb.centralus.cloudapp.azure.com
      LETSENCRYPT_HOST: orelrb.centralus.cloudapp.azure.com
      LETSENCRYPT_EMAIL: karpinovsky@gmail.com
    depends_on:
      - db

  frontend:
    build:
      context: ../orelrb-frontend
      dockerfile: Dockerfile.dev
    command: yarn start
    image: frontend:1
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ../orelrb-frontend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_HOST: orelrb.centralus.cloudapp.azure.com
      LETSENCRYPT_HOST: orelrb.centralus.cloudapp.azure.com
      LETSENCRYPT_EMAIL: karpinovsky@gmail.com
    depends_on:
      - backend
